name: portfolio_node_app

on:
  push:
    branches: [ "main" ]
    

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
            - # checkout to the repository on the build machine
                name: Checkout
                uses: actions/checkout@v3
            - # login to Docker Hub using the secrets provided
                name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOkEN }}
            - # Login to GHCR
              env:
                REGISTRY: ghcr.io
              uses: docker/login-action@v1
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.CR_PAT }}
            - #Login to GCR
              env:
                PROJECT_ID: portfolio-23
                uses: gooogle-github-actions/setup-gcloud@master
                with:
                  version: 'latest'
                  service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
                  project_id: ${{ env.PROJECT_ID }}
                  export_default_credentials: true
            - # GCR: Build Docker Image
                name: Build Docker Image
                env:
                  IMAGE_NAME: portfolio
                  PROJECT_ID: portfolio-23
                  IMAGE_TAG: latest
                run: docker build -t $IMAGE_NAME .
            - #GCR
                name: Configure Docker Client
                run: |-
                  gcloud auth configure-docker

                name: Push Docker Image to GCR
                env:
                  IMAGE_NAME: portfolio
                  PROJECT_ID: portfolio-23
                  IMAGE_TAG: latest
                run: |-
                  docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$IMAGE_TAG
                  docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$IMAGE_TAG
             #tag docker image to gcr image format then push to gcr
                run: |-
                  docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest 
                  docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest 
                  
              - name: Extract metadata (tags, labels) for Docker GHCR
                env:
                  REGISTRY: ghcr.io
                  IMAGE_NAME: ${{ github.repository }}
                id: meta
                uses: docker/metadata-action@v3
                with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} #create ghcr image format within as id called meta
              #GHCR: Build the container image and push it to GHCR
              - name: Build and push Docker image
                  uses: docker/build-push-action@v4 #push docker image to ghcr
                  with:
                    context: .
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
            
            - # DOCKER HUB:create a build kit builder instance
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2
            - # DOCKER HUB:build the container image and push it to Docker \
                name: Build and push to Docker Hub
                uses: docker/build-push-action@v4
                with:
                  context: .
                  file: ./app/backend/Dockerfile
                  push: true
                  tags: conorstreete/portfolio:latest
